### ISSUE TITLE
ev3_link compile error

### ISSUE THREAD

**Issue by dimkatsvetcoff** [in4lio/ev3dev-c#1]
When I try to compile eve_link there is an error:

Undefined reference to 'main' error in crt1.o function _start...

Before adding -nostartfiles flag its compiling. but return an error 

segmentation fault

what can i do?

it was on ubuntu 14

**Comment by yajo10** [comment]
Hallo,
I had the same problem as dimkatsvetcoff. How can I compile directly on the brick?

**Comment by in4lio** [comment]
Hello,
Did you try to run `make` from `ev3_link` folder (on the brick)?
For example:
```
# cd /root/ev3dev-c/source/ev3/ev3_link/
# make
```
