### ISSUE TITLE
Make install assumes existing directories

### ISSUE THREAD

**Issue by JesApp** [in4lio/ev3dev-c#10]
# Problem

The makefile assumes that the directories `D_INSTALL/bin` and `D_INSTALL/include` already exist. This is probably true if `D_INSTALL` has the standard value, i.e. `/usr/local`. However, if we are installing into another directory this is probably not true.

# Use Case

I am cross-compiling and will only statically link to ev3dev-c. I don't want or need to install ev3dev-c to `/usr/local` on my pc, I just want it in a subdirectory in my projects file tree, so I can then give that directory to the linker.

Side note: I'm using cmake to automate this, but this shouldn't make any difference to the makefile.

# Suggested Solution

add `mkdir -p $(D_INSTALL)/lib` and `mkdir -p $(D_INSTALL)/include` to the install function in the makefile. As far as I know, this shouldn't cause any problems if the directories (like `/usr/local/lib` and `/usr/local/include`) already exist, and should solve the problem in other cases.

If you'd like a pull request with this change, just let me know. :)

**Comment by in4lio** [comment]
Yes, thanks! Go ahead!)
