### ISSUE TITLE
Enums in ASM headers ev3_led.h and ev3_light.h are confusing

### ISSUE THREAD

**Issue by tcwan** [in4lio/ev3dev-c#14]
Hi,

After looking at the ev3_led.h and ev3_light.h ASM headers again, I find that the actual ENUMs are difficult to parse from the generated output.
```
.set ENUM_COUNTER, 0
.equiv LIT_OFF, ENUM_COUNTER
.set ENUM_COUNTER, ENUM_COUNTER + 1
.equiv LIT_GREEN, ENUM_COUNTER
.set ENUM_COUNTER, ENUM_COUNTER + 1
.equiv LIT_RED, ENUM_COUNTER
.set ENUM_COUNTER, ENUM_COUNTER + 1
.equiv LIT_AMBER, ENUM_COUNTER
.set ENUM_COUNTER, ENUM_COUNTER + 1

.equiv LIT__COL__, ENUM_COUNTER
```
The expanded macros makes the actual ENUM values LIT_OFF, LIT_GREEN, LIT_RED, and LIT_AMBER difficult to determine.

I realize that these 2 headers depend on a dictionary file. However, is it possible to generate output that is similar to the other ASM include files?
```
#include "enum-asm.h"

ENUM_0 LIT_OFF
ENUM_N LIT_GREEN
ENUM_N LIT_RED
ENUM_N LIT_AMBER
ENUM_N LIT__COL__
```
Not sure whether I specified `LIT__COL__` correctly in the example output.

**Comment by in4lio** [comment]
I replaced all of them with `#define`s.
