### ISSUE TITLE
SyntaxError? ($make in ev3-c/source/ev3)

### ISSUE THREAD

**Issue by aacco** [in4lio/ev3dev-c#17]
In ev3-c/source/ev3, I got below error:

>$ make
>python -u ../../yupp/yup.py -q --pp-browse -d../../source/ev3 ev3_light.yu-h
>  File "../../yupp/yup.py", line 407
>    print PP_I, PP_FILE % fn
>             ^
>SyntaxError: Missing parentheses in call to 'print'. Did you mean print(PP_I, PP_FILE % fn)?
>make: *** [makefile:289: ev3_light.h] Error 1

Should I rewrite?

environment:
archlinux: (May 7, 2018)
ev3dev-c: 1.0c2, 2017-10-13
kernel: 4.4.87-22-ev3dev-ev3
arm-linux-gnueabi-gcc: 8.1.0

Thank you.

**Comment by in4lio** [comment]
Hi @aacco -- your system runs Python 3 by default, but yupp requires Python 2.

**Comment by aacco** [comment]
Thanks!
