### ISSUE TITLE
Plan for ev3dev-stretch support?

### ISSUE THREAD

**Issue by tcwan** [in4lio/ev3dev-c#23]
Hi,
I'd just like to find out what is your plan for ev3dev-stretch support in ev3dev-c?
As I mentioned in Issue #15, the current libraries will not work with the new sysfs naming.

Since there is already a beta release of ev3dev-stretch on Aug 6 2018, I think the actual release will be coming along soon.

**Comment by in4lio** [comment]
Please find initial updates in the "stretch" branch.

**Comment by tcwan** [comment]
Hi,
I've merged the initial 'stretch' updates, but the port detection logic still does not work without the hack from Issue #15

**Comment by tcwan** [comment]
Patches have been merged. Closing this issue.
