### ISSUE TITLE
Please merge the following fixes

### ISSUE THREAD

**Issue by tcwan** [in4lio/ev3dev-c#28]
There are two more fixes to the GPIO_KEYS_PATH constant that needs to be merged:

tcwan/ev3dev-c/stretch branch commits:
72231097daa5217fb52eab93bc86d4a87495d638
605b056d05952b82b0dbcefc681c547dabc014f7

**Comment by tcwan** [comment]
Also, the proposed port prefix parsing logic fixes:
7f06b1aaf70a40daafaa5d6311ef0c23f2f6cbce
5854935fff02f541accc8d5367af73bd64210b58

**Comment by in4lio** [comment]
Merged, Thanks!
