### ISSUE TITLE
python code in c libraries; use of swig etc.

### ISSUE THREAD

**Issue by towtruck1** [in4lio/ev3dev-c#3]
Hello

I am hoping someone can explain the relationship between the python code & C code in the EV3 C libraries. I understand from reading up on SWIG, that C/C++ code can be wrapped for use in scripting languages, however it seems at some point that the opposite is occurring.

For example:
In trying to understand the example (ev3dev-c\eg\tacho\tacho.c) I tried to discover where DESC_LIMIT was declared/defined/set. It is referenced in ev3_tacho.h, but only set in line 133 of ev3.yu-i.

```
#define DESC_LIMIT    64
```
All of which gives me the impression that the C is wrapping something else (whatever *.yu-i is).
I suppose I could spend hours trying to get up to speed on SWIG &/or reverse engineering all this, or maybe someone can be merciful and give me a shove in the right direction. I'm finding the examples don't help me that much if I have to go outside of the *.h or *.c files.

Thanks!

**Comment by in4lio** [comment]
Hello,

**In brief**: I use Python to generate source code of C library, then I use SWIG to create Python library.

The ["yupp"](https://github.com/in4lio/yupp) preprocessor (written on Python) allows me to generate a huge amount of code for objects with identical functionality using the dictionary of properties, see [the dictionary] (https://github.com/in4lio/ev3dev-c/blob/master/source/ev3/ev3_tacho-dict.yu#L37) of tacho's attributes and [generated functions](https://github.com/in4lio/ev3dev-c/blob/master/source/ev3/ev3_tacho.c#L52) to access these attributes.
Also, for example, "yupp" allows to extract sensors types and modes from ["sensors.json"](https://github.com/ev3dev/ev3dev.github.io/blob/master/_data/sensors.json) on "ev3dev" repository and to create corresponding [enumerates](https://github.com/in4lio/ev3dev-c/blob/master/source/ev3/ev3_sensor.h#L75).

For creating Python library we need SWIG interface file and... I use "yupp" ;-)

So, we have next types of file:
`ev3.yu-i` – source of SWIG interface file
`ev3.i` – generated SWIG interface file to create Python library
`*.yu-*, *.yu` – source code of the library on C with using "yupp" preprocessor
`*.c, *.h` – generated source code of C library and examples

Any time!

**Comment by towtruck1** [comment]
Thank You!

That was an awesome explanation. I don't understand it all yet, but now that I get the general picture I can review the files and the documentation for SWIG & yupp and start putting it together. It also gives me some insight into why things look the way they do in the C code. 
Thanks again!
