### ISSUE TITLE
Pull request to fix LED syspath in stretch

### ISSUE THREAD

**Issue by tcwan** [in4lio/ev3dev-c#31]
Sorry, I cannot create a pull request due to the significant divergence between your stretch branch and my current fork.

I've created a specific patch for this issue, it is in the enclosed file.

[0001-Fix-stretch-LED-syspath-naming.patch.txt](https://github.com/in4lio/ev3dev-c/files/3797182/0001-Fix-stretch-LED-syspath-naming.patch.txt)

**Comment by will-tam** [comment]
Hello everybody.

Thanks you  tcwan to write an issue about it, and mkfoote about you diff, i just have applied the update to my brick, and of course saw this ranaming in /sys/class/leds.

I would write an issue about this point, and propose a correction in these examples.
Best regards.

**Comment by will-tam** [comment]
Hello everybody.

Thanks you  tcwan to write an issue about it, and mkfoote about you diff, i just have applied the update to my brick, and of course saw this ranaming in /sys/class/leds.

I would write an issue about this point, and propose a correction in these examples.
Best regards.

**Comment by in4lio** [comment]
`streatch` is the default branch now, please rebase the branch with fixes if the PR is still actual.
