### ISSUE TITLE
Device mapping error?

### ISSUE THREAD

**Issue by PeterTinBrisbane** [in4lio/ev3dev-c#33]
I very recently installed ev3dev, followed instructions, downloaded and built ev3dev-c library - all good
followed a number the examples and noticed that the sensors.c output correctly identified the devices plugged in but NEVER gave a valid port. 

ev3_sensor[3]
  type = lego-ev3-color
  port = <unknown>
  mode = COL-REFLECT
  value[0] = 0

Similar issue with testing motors...

I installed gdb and went digging and realized that the issue is in ev3_port.c in the function ev3_parse_port_name().  All of the name strings being passed in have a prefix of "ev3-ports:".

adding the following lines ahead of the first 'if' statement in that function fixed the problem:
    if( strncmp( name, "ev3-ports:", 10 ) == 0 )
    { 
	name += 10;
    }

ev3_sensor[3]
  type = lego-ev3-color
  port = in3
  mode = COL-COLOR
  value[0] = 0

detials of installation:
uname -a
Linux ev3dev 4.14.117-ev3dev-2.3.5-ev3 #1 PREEMPT Sat Mar 7 12:54:39 CST 2020 armv5tejl GNU/Linux

the README in the ev3dev-c source tree reports:  ev3dev-c    1.0c3     2019-01-27

Hope this helps
PeterT

**Comment by PeterTinBrisbane** [comment]
sorry the first "port=" should have read "port=<unknown>"

**Comment by PeterTinBrisbane** [comment]
sorry the first "port=" should have read "port=<<unknown>>"

**Comment by PeterTinBrisbane** [comment]
Not sure how I closed this - so re-opening now.

**Comment by tcwan** [comment]
Are you using ev3dev for the stretch distro? You need to switch to the stretch branch
```
$ cd <ev3dev-c path>
$ git checkout stretch
```

The master branch is meant for jessie.

**Comment by PeterTinBrisbane** [comment]
Just followed the instructions on the web page so I'm not sure but I'm pretty sure that I grabbed the master branch.
I wont have the chance to verify it until tomorrow - I'll let you know
Thanks

**Comment by PeterTinBrisbane** [comment]
Thanks that seems to have sorted the issue,,,
