### ISSUE TITLE
UDP socket not closed under WIN32

### ISSUE THREAD

**Issue by T12z** [in4lio/ev3dev-c#4]
Frankly, this is what one hates Windows programming for:

Short: you cannot use `close(sockfd)` (see source/ev3/ev3_link/ev3_link.c ) to close a WSA/winsock socket. It needs to be `closesocket()`. This only comes to attention, when you embed the library into something longer running.
Yes, I found that out the hard way.

Anyways, top library!!

**Comment by in4lio** [comment]
Thanks! Fixed.
