### ISSUE TITLE
Can't get HiTechnic IR Seeker v2 working

### ISSUE THREAD

**Issue by matanui159** [in4lio/ev3dev-c#5]
First off, the sensor itself is working, I can go into Device Browser and it reads the correct values.
Secondly, I can get it to work normally using `set_sensor_mode` and `get_sensor_value<n>`.

However, I'm trying to recreate HiTechnic's "enhanced" function they coded for NXC, so going through their source code I came to the immediate issue of not having any function similar to I2CBytes, so I made my own:
```C
typedef unsigned char BYTE;

static void get_sensor_all(BYTE port, char* mode, BYTE* buffer, int off, int len) {
    set_sensor_mode(port, mode);
    int value;
    printf("%s:\t", mode); // for testing
    for (int i = 0; i < len; ++i) {
        get_sensor_value(i + off, port, &value);
        printf("%i\t", value); // for testing
        buffer[i] = (BYTE)value;
    }
    printf("\n"); // for testing
}
```

But it all the output values were 10 no matter what I did. So I added this between `int value` and the first `printf`:
```C
for (int j = 0; j < 100; ++j) {
    for (int i = 0; i < len; ++i) {
        get_sensor_value(i + off, port, &value);
    }
}
```
My thinking behind this that I needed a bit of time between setting the mode and the final reading, however this caused the outputs to be some crazy large negative numbers.

PS. I need to be able to switch between sensor modes because I need both AC and DC information.

**Comment by in4lio** [comment]
Hi @matanui159 -- I think, you're right -- a short pause between the mode changing and the values reading is required. Something like:
```cpp
usleep(100 * 1000); /* Sleep 100 msec */`
```
About _"crazy large negative numbers"_ -- could you check values into `/sys/class/lego-sensor/.../valueX.` files manually? Are that values _"crazy"_ too? Unfortunately, I have no a sensor of that type and can not check that issue myself.

**Comment by matanui159** [comment]
What of the things I tried was adding a 100ms delay between setting the mode and reading the values and I still got 10. And even if it did work I need to get these values quickly as I will be switching modes alot so a total of 200ms to read both DC-ALL and AC-ALL is not optimal.

Along with this, I have checked the built-in sensor reader and I can successfully read values from it (well, the first value at-least, but that's enough to prove that it works)

**Comment by matanui159** [comment]
An update on the issue `set_sensor_mode` doesn't seem to work full-stop. Unless I'm doing something wrong, something like:
```C
set_sensor_mode(socket_to_port(IN1), "AC-ALL");
```
doesn't work, however, setting the mode in the Device Browser while the program is running does work.

**Comment by matanui159** [comment]
Nevermind, didn't know there was an extra step needed (`ev3_search_*`)

**Comment by in4lio** [comment]
Hi! A small example just to begin with:

```cpp
// Here will be Sequence Number of a sensor (a number at the end of sensor's folder name)
// NOT a port.
uint8_t sn_ir;

 // Looks for sensors and makes a roster.
ev3_sensor_init();

// Gets Sequence Number of the HT_NXT_IR_SEEK_V2 sensor from the roster.
if ( ev3_search_sensor( HT_NXT_IR_SEEK_V2, &sn_ir, 0 )) { 
	printf( "IR sensor is found\n" );
} else {
	printf( "IR sensor is NOT found\n" );
}

// Sets a mode by its name.
set_sensor_mode( sn_ir, "AC-ALL" );
// OR
// Set a mode using a mode's ID.
set_sensor_mode_inx( sn_ir, HT_NXT_IR_SEEK_V2_AC_ALL );
```
`socket_to_port()` from `BRICK` library isn't the right choice in this case.
