### ISSUE TITLE
Current docker images from ev3dev does not include python interpreter

### ISSUE THREAD

**Issue by tcwan** [in4lio/ev3dev-c#8]
I'm starting on ev3dev-c as my target language for EV3 development, and I'd just like to mention that the building inside docker guide is not working with the default ev3dev-cross Docker images, since they don't come with python installed.

It might be fine for someone familiar with docker and how to keep updated containers around, but I think there would be a problem in the following cases if someone is using the default docker images:

1. The existing SKIP_PP checks will skip header generation inside the Docker image since `__ARM_ARCH_4T__` always evaluate to TRUE. (incidentally this is a rather fragile test since the Host-based Carlson-Minot Cross-compilers just happen to **NOT** support ARMv4T output. Would `/proc/cpuinfo` be a better test?)
2. 'make clean; make' will fail inside the docker container, since the *.h and *.c file cannot be regenerated.
3. I cannot generate the *.c files easily outside the Docker environment (assuming that i don't have arm-linux-gnueabi-gcc installed for the Host), since make does not create all the necessary files in one step. (It'll generate one .c and then try to run gcc on it).

Is it possible to cause the *.c and *.h generation step to be done in one shot, so that it can at least avoid problem #3? Alternatively python would have to  be included as part of the ev3dev-cross images.

**Comment by tcwan** [comment]
With reference to the docker image, I found out that you have a dockerfile which installs the python interpreter. However, I think it is a bit confusing to refer to it as ev3cc in the README since it is different from the one from ev3dev.

**Comment by in4lio** [comment]
Hi @tcwan 
Thank you for your comment, I agree, it can be misinterpreted, I will correct the README.
