### ISSUE TITLE
How do I generate the *.h and *.c files using yupp?

### ISSUE THREAD

**Issue by tcwan** [in4lio/ev3dev-c#9]
Hi,

I'm trying to port ev3dev-c to run on ev3-stretch, and the `/sys/class` hierarchy has changed, notably for the LED controls (this is the first device driver I'm trying to port). I understand that the definitions are found in `ev3-led-dict.yu`.

However, I can't find any information regarding how to use yupp to regenerate the `*.h` and `*.c` files after modifying the `*.yu` file.

**Comment by in4lio** [comment]
Hi @tcwan

You should rebuild the library on PC (under Windows, for example). Before that, please run `make clean`, just in case)).

If you want to perform preprocessing on the brick, you should set `SKIP_PP = 0` in the makefile. But be patient, running the preprocessor on the brick takes some time.

**Comment by tcwan** [comment]
Doh! I forgot to check the beginning of the makefile. I'd even made a comment regarding the `__ARM_ARCH_4T__` failing inside docker in an earlier issue.

BTW, I don't plan to use the brick to compile the code.

**Comment by in4lio** [comment]
I will add info about `SKIP_PP` into README.
